### ISSUE TITLE
Despawning a particle system doesn't despawn the particles

### ISSUE THREAD

**Issue by darthdeus** [abnormalbrain/bevy_particle_systems#20]
It seems since the update to bevy 0.9 that despawning a `ParticleSystem` doesn't despawn its `Particle`s. Cleaning them up manually works, but in the previous version this wasn't required.

**Comment by abnormalbrain** [comment]
@darthdeus Can you add a bit more detail about the setup of your particle system? The most relevant details would be whether it's using local space or world space. And how you're despawning the system?

**Comment by abnormalbrain** [comment]
https://github.com/abnormalbrain/bevy_particle_systems/pull/16/files#diff-420f4e08a25299e0e1fb09f4757e1d5d027a2278f37030c09ab9c06786cfa52eR202-R209

It looks like previously lifetime would keep incrementing by a non-scaled time value even once the parent was no longer available. Now lifetime stops incrementing so they never get picked up by the cleanup system due to the lifetime expiration. 

So we can restore the previous behavior, but this will still behave incorrectly for particle systems that are despawned while scaled time is in use. But I'll file that as another bug.

**Comment by abnormalbrain** [comment]
@darthdeus #21 should provide more-or-less the same behavior as before, with a little added configurability. If your particles are very short lived, there's likely not much difference between despawning when the system is removed vs (correctly) despawning when the particle lifetime ends.
